services:
  # PostgreSQL Database
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: elevatehire_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: priyantha2002
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for Celery
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6380:6379"

  # Django Backend
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=1
      - PRODUCTION_MODE=false
      - DATABASE_URL=postgresql://postgres:priyantha2002@db:5432/elevatehire_db
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - ./backend:/app  # Mount local backend code into the container
      - backend_static:/app/static
      - backend_media:/app/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  # Celery Worker
  celery:
    build: ./backend
    restart: always
    env_file:
      - .env
    environment:
      - DEBUG=1
      - PRODUCTION_MODE=false
      - DATABASE_URL=postgresql://postgres:priyantha2002@db:5432/elevatehire_db
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
      - backend
    command: celery -A core worker -l info

  # Next.js Frontend
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app  # Mount local frontend code into the container
      - /app/node_modules  # Keep node_modules in the container
      - /app/.next  # Cache for Next.js
    depends_on:
      - backend

  # pgAdmin - Database GUI
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@elevatehire.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  backend_static:
  backend_media:
  pgadmin_data:
