version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: elevatehire_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dinesh2002
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for Celery
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  # Django Backend
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:Dinesh2002@db:5432/elevatehire_db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app
      - backend_static:/app/static
      - backend_media:/app/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  # Celery Worker
  celery:
    build: ./backend
    restart: always
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:Dinesh2002@db:5432/elevatehire_db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
      - backend
    command: celery -A core worker -l info

  # Next.js Frontend
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

volumes:
  postgres_data:
  backend_static:
  backend_media:
