# Generated by Django 5.2.4 on 2025-10-01 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='ai_analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='AI analysis processing status', max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='ai_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Key topics and keywords identified'),
        ),
        migrations.AddField(
            model_name='interview',
            name='ai_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='ai_recommendations',
            field=models.JSONField(blank=True, default=list, help_text='AI-generated recommendations'),
        ),
        migrations.AddField(
            model_name='interview',
            name='ai_sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI-generated interview summary'),
        ),
        migrations.AddField(
            model_name='interview',
            name='communication_score',
            field=models.FloatField(blank=True, help_text='Communication skills score', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='interview',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='Confidence percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='interview',
            name='engagement_score',
            field=models.FloatField(blank=True, help_text='Engagement level score', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='interview',
            name='technical_score',
            field=models.FloatField(blank=True, help_text='Technical skills score', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='interview',
            name='transcript',
            field=models.TextField(blank=True, help_text='Interview transcript'),
        ),
        migrations.AddField(
            model_name='interview',
            name='video_file',
            field=models.FileField(blank=True, help_text='Interview recording for AI analysis', null=True, upload_to='interview_videos/'),
        ),
    ]
